// Generated by Haxe 5.0.0-alpha.1+1423a5f
#ifndef INCLUDED_pi_xy_algo_IhitObj
#define INCLUDED_pi_xy_algo_IhitObj

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS2(pi_xy,algo,IhitObj)

namespace pi_xy{
namespace algo{


class HXCPP_CLASS_ATTRIBUTES IhitObj_obj {
	public:
		typedef ::hx::Object super;
		HX_DO_INTERFACE_RTTI;

};

} // end namespace pi_xy
} // end namespace algo

#endif /* INCLUDED_pi_xy_algo_IhitObj */ 
