// Generated by Haxe 5.0.0-alpha.1+1423a5f
#ifndef INCLUDED_iterMagic_Iimg
#define INCLUDED_iterMagic_Iimg

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS1(iterMagic,Iimg)

namespace iterMagic{


class HXCPP_CLASS_ATTRIBUTES Iimg_obj {
	public:
		typedef ::hx::Object super;
		HX_DO_INTERFACE_RTTI;

		int (::hx::Object :: *_hx_set)(int index,int value); 
		static inline int set( ::Dynamic _hx_,int index,int value) {
			return (_hx_.mPtr->*( ::hx::interface_cast< ::iterMagic::Iimg_obj *>(_hx_.mPtr->_hx_getInterface(0xed2c7ccf)))->_hx_set)(index,value);
		}
		int (::hx::Object :: *_hx_get)(int index); 
		static inline int get( ::Dynamic _hx_,int index) {
			return (_hx_.mPtr->*( ::hx::interface_cast< ::iterMagic::Iimg_obj *>(_hx_.mPtr->_hx_getInterface(0xed2c7ccf)))->_hx_get)(index);
		}
};

} // end namespace iterMagic

#endif /* INCLUDED_iterMagic_Iimg */ 
