// Generated by Haxe 5.0.0-alpha.1+1423a5f
#include <hxcpp.h>

#ifndef INCLUDED_haxe_io_Bytes
#include <haxe/io/Bytes.h>
#endif
#ifndef INCLUDED_haxe_io_Input
#include <haxe/io/Input.h>
#endif
#ifndef INCLUDED_sys_io__Process_Stdout
#include <sys/io/_Process/Stdout.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_af8058f8f53c9e57_61_new,"sys.io._Process.Stdout","new",0xc765a8f4,"sys.io._Process.Stdout.new","sys/io/Process.hx",61,0x38a91ed6)
namespace sys{
namespace io{
namespace _Process{

void Stdout_obj::__construct( ::Dynamic p,bool out){
            	HX_STACKFRAME(&_hx_pos_af8058f8f53c9e57_61_new)
HXLINE(  62)		this->p = p;
HXLINE(  63)		this->out = out;
HXLINE(  64)		this->buf = ::haxe::io::Bytes_obj::alloc(1);
            	}

Dynamic Stdout_obj::__CreateEmpty() { return new Stdout_obj; }

void *Stdout_obj::_hx_vtable = 0;

Dynamic Stdout_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< Stdout_obj > _hx_result = new Stdout_obj();
	_hx_result->__construct(inArgs[0],inArgs[1]);
	return _hx_result;
}

bool Stdout_obj::_hx_isInstanceOf(int inClassId) {
	if (inClassId<=(int)0x19e22056) {
		return inClassId==(int)0x00000001 || inClassId==(int)0x19e22056;
	} else {
		return inClassId==(int)0x2316116e;
	}
}


::hx::ObjectPtr< Stdout_obj > Stdout_obj::__new( ::Dynamic p,bool out) {
	::hx::ObjectPtr< Stdout_obj > __this = new Stdout_obj();
	__this->__construct(p,out);
	return __this;
}

::hx::ObjectPtr< Stdout_obj > Stdout_obj::__alloc(::hx::Ctx *_hx_ctx, ::Dynamic p,bool out) {
	Stdout_obj *__this = (Stdout_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(Stdout_obj), true, "sys.io._Process.Stdout"));
	*(void **)__this = Stdout_obj::_hx_vtable;
	__this->__construct(p,out);
	return __this;
}

Stdout_obj::Stdout_obj()
{
}

void Stdout_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(Stdout);
	HX_MARK_MEMBER_NAME(p,"p");
	HX_MARK_MEMBER_NAME(out,"out");
	HX_MARK_MEMBER_NAME(buf,"buf");
	HX_MARK_END_CLASS();
}

void Stdout_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(p,"p");
	HX_VISIT_MEMBER_NAME(out,"out");
	HX_VISIT_MEMBER_NAME(buf,"buf");
}

::hx::Val Stdout_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 1:
		if (HX_FIELD_EQ(inName,"p") ) { return ::hx::Val( p ); }
		break;
	case 3:
		if (HX_FIELD_EQ(inName,"out") ) { return ::hx::Val( out ); }
		if (HX_FIELD_EQ(inName,"buf") ) { return ::hx::Val( buf ); }
	}
	return super::__Field(inName,inCallProp);
}

::hx::Val Stdout_obj::__SetField(const ::String &inName,const ::hx::Val &inValue,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 1:
		if (HX_FIELD_EQ(inName,"p") ) { p=inValue.Cast<  ::Dynamic >(); return inValue; }
		break;
	case 3:
		if (HX_FIELD_EQ(inName,"out") ) { out=inValue.Cast< bool >(); return inValue; }
		if (HX_FIELD_EQ(inName,"buf") ) { buf=inValue.Cast<  ::haxe::io::Bytes >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void Stdout_obj::__GetFields(Array< ::String> &outFields)
{
	outFields->push(HX_("p",70,00,00,00));
	outFields->push(HX_("out",8e,a0,54,00));
	outFields->push(HX_("buf",33,c3,4a,00));
	super::__GetFields(outFields);
};

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo Stdout_obj_sMemberStorageInfo[] = {
	{::hx::fsObject /*  ::Dynamic */ ,(int)offsetof(Stdout_obj,p),HX_("p",70,00,00,00)},
	{::hx::fsBool,(int)offsetof(Stdout_obj,out),HX_("out",8e,a0,54,00)},
	{::hx::fsObject /*  ::haxe::io::Bytes */ ,(int)offsetof(Stdout_obj,buf),HX_("buf",33,c3,4a,00)},
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo *Stdout_obj_sStaticStorageInfo = 0;
#endif

static ::String Stdout_obj_sMemberFields[] = {
	HX_("p",70,00,00,00),
	HX_("out",8e,a0,54,00),
	HX_("buf",33,c3,4a,00),
	::String(null()) };

::hx::Class Stdout_obj::__mClass;

void Stdout_obj::__register()
{
	Stdout_obj _hx_dummy;
	Stdout_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("sys.io._Process.Stdout",02,5f,41,bc);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &::hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(0 /* sStaticFields */);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(Stdout_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< Stdout_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = Stdout_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = Stdout_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace sys
} // end namespace io
} // end namespace _Process
