// Generated by Haxe 5.0.0-alpha.1+1423a5f
#ifndef INCLUDED_haxe_ds_GenericStack_Int
#define INCLUDED_haxe_ds_GenericStack_Int

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_STACK_FRAME(_hx_pos_3961c4e86dc3b25e_107_new)
HX_DECLARE_CLASS2(haxe,ds,GenericCell_Int)
HX_DECLARE_CLASS2(haxe,ds,GenericStack_Int)

namespace haxe{
namespace ds{


class HXCPP_CLASS_ATTRIBUTES GenericStack_Int_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef GenericStack_Int_obj OBJ_;
		GenericStack_Int_obj();

	public:
		enum { _hx_ClassId = 0x4fce5456 };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="haxe.ds.GenericStack_Int")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,true,"haxe.ds.GenericStack_Int"); }

		inline static ::hx::ObjectPtr< GenericStack_Int_obj > __new() {
			::hx::ObjectPtr< GenericStack_Int_obj > __this = new GenericStack_Int_obj();
			__this->__construct();
			return __this;
		}

		inline static ::hx::ObjectPtr< GenericStack_Int_obj > __alloc(::hx::Ctx *_hx_ctx) {
			GenericStack_Int_obj *__this = (GenericStack_Int_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(GenericStack_Int_obj), true, "haxe.ds.GenericStack_Int"));
			*(void **)__this = GenericStack_Int_obj::_hx_vtable;
{
            	HX_STACKFRAME(&_hx_pos_3961c4e86dc3b25e_107_new)
            	}
		
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~GenericStack_Int_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("GenericStack_Int",21,84,4c,31); }

		 ::haxe::ds::GenericCell_Int head;
};

} // end namespace haxe
} // end namespace ds

#endif /* INCLUDED_haxe_ds_GenericStack_Int */ 
