// Generated by Haxe 5.0.0-alpha.1+1423a5f
#include <hxcpp.h>

#ifndef INCLUDED_iterMagic_ArrIntImg
#include <iterMagic/ArrIntImg.h>
#endif
#ifndef INCLUDED_iterMagic_Iimg
#include <iterMagic/Iimg.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_62e17d0bd1821534_124_new,"iterMagic.ArrIntImg","new",0xd35d89ae,"iterMagic.ArrIntImg.new","iterMagic/Img.hx",124,0x8899afd5)
HX_LOCAL_STACK_FRAME(_hx_pos_62e17d0bd1821534_126_set,"iterMagic.ArrIntImg","set",0xd36154f0,"iterMagic.ArrIntImg.set","iterMagic/Img.hx",126,0x8899afd5)
HX_LOCAL_STACK_FRAME(_hx_pos_62e17d0bd1821534_132_get,"iterMagic.ArrIntImg","get",0xd35839e4,"iterMagic.ArrIntImg.get","iterMagic/Img.hx",132,0x8899afd5)
namespace iterMagic{

void ArrIntImg_obj::__construct(){
            	HX_STACKFRAME(&_hx_pos_62e17d0bd1821534_124_new)
            	}

Dynamic ArrIntImg_obj::__CreateEmpty() { return new ArrIntImg_obj; }

void *ArrIntImg_obj::_hx_vtable = 0;

Dynamic ArrIntImg_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< ArrIntImg_obj > _hx_result = new ArrIntImg_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool ArrIntImg_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x71ed54a0;
}

static ::iterMagic::Iimg_obj _hx_iterMagic_ArrIntImg__hx_iterMagic_Iimg= {
	( int (::hx::Object::*)(int,int))&::iterMagic::ArrIntImg_obj::set,
	( int (::hx::Object::*)(int))&::iterMagic::ArrIntImg_obj::get,
};

void *ArrIntImg_obj::_hx_getInterface(int inHash) {
	switch(inHash) {
		case (int)0xed2c7ccf: return &_hx_iterMagic_ArrIntImg__hx_iterMagic_Iimg;
	}
	#ifdef HXCPP_SCRIPTABLE
	return super::_hx_getInterface(inHash);
	#else
	return 0;
	#endif
}

int ArrIntImg_obj::set(int index,int value){
            	HX_STACKFRAME(&_hx_pos_62e17d0bd1821534_126_set)
HXLINE( 127)		this->data[index] = value;
HXLINE( 128)		return value;
            	}


HX_DEFINE_DYNAMIC_FUNC2(ArrIntImg_obj,set,return )

int ArrIntImg_obj::get(int index){
            	HX_STACKFRAME(&_hx_pos_62e17d0bd1821534_132_get)
HXDLIN( 132)		return this->data->__get(index);
            	}


HX_DEFINE_DYNAMIC_FUNC1(ArrIntImg_obj,get,return )


::hx::ObjectPtr< ArrIntImg_obj > ArrIntImg_obj::__new() {
	::hx::ObjectPtr< ArrIntImg_obj > __this = new ArrIntImg_obj();
	__this->__construct();
	return __this;
}

::hx::ObjectPtr< ArrIntImg_obj > ArrIntImg_obj::__alloc(::hx::Ctx *_hx_ctx) {
	ArrIntImg_obj *__this = (ArrIntImg_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(ArrIntImg_obj), true, "iterMagic.ArrIntImg"));
	*(void **)__this = ArrIntImg_obj::_hx_vtable;
	__this->__construct();
	return __this;
}

ArrIntImg_obj::ArrIntImg_obj()
{
}

void ArrIntImg_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(ArrIntImg);
	HX_MARK_MEMBER_NAME(data,"data");
	HX_MARK_MEMBER_NAME(width,"width");
	HX_MARK_MEMBER_NAME(height,"height");
	HX_MARK_MEMBER_NAME(length,"length");
	HX_MARK_END_CLASS();
}

void ArrIntImg_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(data,"data");
	HX_VISIT_MEMBER_NAME(width,"width");
	HX_VISIT_MEMBER_NAME(height,"height");
	HX_VISIT_MEMBER_NAME(length,"length");
}

::hx::Val ArrIntImg_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"set") ) { return ::hx::Val( set_dyn() ); }
		if (HX_FIELD_EQ(inName,"get") ) { return ::hx::Val( get_dyn() ); }
		break;
	case 4:
		if (HX_FIELD_EQ(inName,"data") ) { return ::hx::Val( data ); }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"width") ) { return ::hx::Val( width ); }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"height") ) { return ::hx::Val( height ); }
		if (HX_FIELD_EQ(inName,"length") ) { return ::hx::Val( length ); }
	}
	return super::__Field(inName,inCallProp);
}

::hx::Val ArrIntImg_obj::__SetField(const ::String &inName,const ::hx::Val &inValue,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 4:
		if (HX_FIELD_EQ(inName,"data") ) { data=inValue.Cast< ::Array< int > >(); return inValue; }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"width") ) { width=inValue.Cast< int >(); return inValue; }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"height") ) { height=inValue.Cast< int >(); return inValue; }
		if (HX_FIELD_EQ(inName,"length") ) { length=inValue.Cast< int >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void ArrIntImg_obj::__GetFields(Array< ::String> &outFields)
{
	outFields->push(HX_("data",2a,56,63,42));
	outFields->push(HX_("width",06,b6,62,ca));
	outFields->push(HX_("height",e7,07,4c,02));
	outFields->push(HX_("length",e6,94,07,9f));
	super::__GetFields(outFields);
};

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo ArrIntImg_obj_sMemberStorageInfo[] = {
	{::hx::fsObject /* ::Array< int > */ ,(int)offsetof(ArrIntImg_obj,data),HX_("data",2a,56,63,42)},
	{::hx::fsInt,(int)offsetof(ArrIntImg_obj,width),HX_("width",06,b6,62,ca)},
	{::hx::fsInt,(int)offsetof(ArrIntImg_obj,height),HX_("height",e7,07,4c,02)},
	{::hx::fsInt,(int)offsetof(ArrIntImg_obj,length),HX_("length",e6,94,07,9f)},
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo *ArrIntImg_obj_sStaticStorageInfo = 0;
#endif

static ::String ArrIntImg_obj_sMemberFields[] = {
	HX_("data",2a,56,63,42),
	HX_("width",06,b6,62,ca),
	HX_("height",e7,07,4c,02),
	HX_("length",e6,94,07,9f),
	HX_("set",a2,9b,57,00),
	HX_("get",96,80,4e,00),
	::String(null()) };

::hx::Class ArrIntImg_obj::__mClass;

void ArrIntImg_obj::__register()
{
	ArrIntImg_obj _hx_dummy;
	ArrIntImg_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("iterMagic.ArrIntImg",bc,da,57,23);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &::hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(0 /* sStaticFields */);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(ArrIntImg_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< ArrIntImg_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = ArrIntImg_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = ArrIntImg_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace iterMagic
