// Generated by Haxe 5.0.0-alpha.1+1423a5f
#include <hxcpp.h>

#ifndef INCLUDED_haxe_io_ArrayBufferViewImpl
#include <haxe/io/ArrayBufferViewImpl.h>
#endif
#ifndef INCLUDED_haxe_io_Bytes
#include <haxe/io/Bytes.h>
#endif
#ifndef INCLUDED_iterMagic_Iimg
#include <iterMagic/Iimg.h>
#endif
#ifndef INCLUDED_iterMagic_U32ArrImg
#include <iterMagic/U32ArrImg.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_d646bfb598621de7_298_new,"iterMagic.U32ArrImg","new",0xb7bd8e2f,"iterMagic.U32ArrImg.new","iterMagic/Img.hx",298,0x8899afd5)
HX_LOCAL_STACK_FRAME(_hx_pos_d646bfb598621de7_300_set,"iterMagic.U32ArrImg","set",0xb7c15971,"iterMagic.U32ArrImg.set","iterMagic/Img.hx",300,0x8899afd5)
HX_LOCAL_STACK_FRAME(_hx_pos_d646bfb598621de7_306_get,"iterMagic.U32ArrImg","get",0xb7b83e65,"iterMagic.U32ArrImg.get","iterMagic/Img.hx",306,0x8899afd5)
namespace iterMagic{

void U32ArrImg_obj::__construct(){
            	HX_STACKFRAME(&_hx_pos_d646bfb598621de7_298_new)
            	}

Dynamic U32ArrImg_obj::__CreateEmpty() { return new U32ArrImg_obj; }

void *U32ArrImg_obj::_hx_vtable = 0;

Dynamic U32ArrImg_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< U32ArrImg_obj > _hx_result = new U32ArrImg_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool U32ArrImg_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x047548f9;
}

static ::iterMagic::Iimg_obj _hx_iterMagic_U32ArrImg__hx_iterMagic_Iimg= {
	( int (::hx::Object::*)(int,int))&::iterMagic::U32ArrImg_obj::set,
	( int (::hx::Object::*)(int))&::iterMagic::U32ArrImg_obj::get,
};

void *U32ArrImg_obj::_hx_getInterface(int inHash) {
	switch(inHash) {
		case (int)0xed2c7ccf: return &_hx_iterMagic_U32ArrImg__hx_iterMagic_Iimg;
	}
	#ifdef HXCPP_SCRIPTABLE
	return super::_hx_getInterface(inHash);
	#else
	return 0;
	#endif
}

int U32ArrImg_obj::set(int index,int value){
            	HX_STACKFRAME(&_hx_pos_d646bfb598621de7_300_set)
HXLINE( 301)		{
HXLINE( 301)			 ::haxe::io::ArrayBufferViewImpl this1 = this->data;
HXDLIN( 301)			bool _hx_tmp;
HXDLIN( 301)			if ((index >= 0)) {
HXLINE( 301)				_hx_tmp = (index < (this1->byteLength >> 2));
            			}
            			else {
HXLINE( 301)				_hx_tmp = false;
            			}
HXDLIN( 301)			if (_hx_tmp) {
HXLINE( 301)				 ::haxe::io::Bytes _this = this1->bytes;
HXDLIN( 301)				int pos = ((index << 2) + this1->byteOffset);
HXDLIN( 301)				_this->b[pos] = ( (unsigned char)(value) );
HXDLIN( 301)				_this->b[(pos + 1)] = ( (unsigned char)((value >> 8)) );
HXDLIN( 301)				_this->b[(pos + 2)] = ( (unsigned char)((value >> 16)) );
HXDLIN( 301)				_this->b[(pos + 3)] = ( (unsigned char)(::hx::UShr(value,24)) );
            			}
            		}
HXLINE( 302)		return value;
            	}


HX_DEFINE_DYNAMIC_FUNC2(U32ArrImg_obj,set,return )

int U32ArrImg_obj::get(int index){
            	HX_STACKFRAME(&_hx_pos_d646bfb598621de7_306_get)
HXDLIN( 306)		 ::haxe::io::ArrayBufferViewImpl this1 = this->data;
HXDLIN( 306)		 ::haxe::io::Bytes _this = this1->bytes;
HXDLIN( 306)		int pos = ((index << 2) + this1->byteOffset);
HXDLIN( 306)		return (((( (int)(_this->b->__get(pos)) ) | (( (int)(_this->b->__get((pos + 1))) ) << 8)) | (( (int)(_this->b->__get((pos + 2))) ) << 16)) | (( (int)(_this->b->__get((pos + 3))) ) << 24));
            	}


HX_DEFINE_DYNAMIC_FUNC1(U32ArrImg_obj,get,return )


::hx::ObjectPtr< U32ArrImg_obj > U32ArrImg_obj::__new() {
	::hx::ObjectPtr< U32ArrImg_obj > __this = new U32ArrImg_obj();
	__this->__construct();
	return __this;
}

::hx::ObjectPtr< U32ArrImg_obj > U32ArrImg_obj::__alloc(::hx::Ctx *_hx_ctx) {
	U32ArrImg_obj *__this = (U32ArrImg_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(U32ArrImg_obj), true, "iterMagic.U32ArrImg"));
	*(void **)__this = U32ArrImg_obj::_hx_vtable;
	__this->__construct();
	return __this;
}

U32ArrImg_obj::U32ArrImg_obj()
{
}

void U32ArrImg_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(U32ArrImg);
	HX_MARK_MEMBER_NAME(data,"data");
	HX_MARK_MEMBER_NAME(width,"width");
	HX_MARK_MEMBER_NAME(height,"height");
	HX_MARK_MEMBER_NAME(length,"length");
	HX_MARK_END_CLASS();
}

void U32ArrImg_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(data,"data");
	HX_VISIT_MEMBER_NAME(width,"width");
	HX_VISIT_MEMBER_NAME(height,"height");
	HX_VISIT_MEMBER_NAME(length,"length");
}

::hx::Val U32ArrImg_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"set") ) { return ::hx::Val( set_dyn() ); }
		if (HX_FIELD_EQ(inName,"get") ) { return ::hx::Val( get_dyn() ); }
		break;
	case 4:
		if (HX_FIELD_EQ(inName,"data") ) { return ::hx::Val( data ); }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"width") ) { return ::hx::Val( width ); }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"height") ) { return ::hx::Val( height ); }
		if (HX_FIELD_EQ(inName,"length") ) { return ::hx::Val( length ); }
	}
	return super::__Field(inName,inCallProp);
}

::hx::Val U32ArrImg_obj::__SetField(const ::String &inName,const ::hx::Val &inValue,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 4:
		if (HX_FIELD_EQ(inName,"data") ) { data=inValue.Cast<  ::haxe::io::ArrayBufferViewImpl >(); return inValue; }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"width") ) { width=inValue.Cast< int >(); return inValue; }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"height") ) { height=inValue.Cast< int >(); return inValue; }
		if (HX_FIELD_EQ(inName,"length") ) { length=inValue.Cast< int >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void U32ArrImg_obj::__GetFields(Array< ::String> &outFields)
{
	outFields->push(HX_("data",2a,56,63,42));
	outFields->push(HX_("width",06,b6,62,ca));
	outFields->push(HX_("height",e7,07,4c,02));
	outFields->push(HX_("length",e6,94,07,9f));
	super::__GetFields(outFields);
};

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo U32ArrImg_obj_sMemberStorageInfo[] = {
	{::hx::fsObject /*  ::haxe::io::ArrayBufferViewImpl */ ,(int)offsetof(U32ArrImg_obj,data),HX_("data",2a,56,63,42)},
	{::hx::fsInt,(int)offsetof(U32ArrImg_obj,width),HX_("width",06,b6,62,ca)},
	{::hx::fsInt,(int)offsetof(U32ArrImg_obj,height),HX_("height",e7,07,4c,02)},
	{::hx::fsInt,(int)offsetof(U32ArrImg_obj,length),HX_("length",e6,94,07,9f)},
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo *U32ArrImg_obj_sStaticStorageInfo = 0;
#endif

static ::String U32ArrImg_obj_sMemberFields[] = {
	HX_("data",2a,56,63,42),
	HX_("width",06,b6,62,ca),
	HX_("height",e7,07,4c,02),
	HX_("length",e6,94,07,9f),
	HX_("set",a2,9b,57,00),
	HX_("get",96,80,4e,00),
	::String(null()) };

::hx::Class U32ArrImg_obj::__mClass;

void U32ArrImg_obj::__register()
{
	U32ArrImg_obj _hx_dummy;
	U32ArrImg_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("iterMagic.U32ArrImg",bd,4a,d9,3e);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &::hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(0 /* sStaticFields */);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(U32ArrImg_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< U32ArrImg_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = U32ArrImg_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = U32ArrImg_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace iterMagic
